Repository pheature-flags/toggle-core, pull requests merged in 2021-11, with the labels that each got.

#40 [#39] Update PhpStan to version 1 and level 9
  composer.json
  src/Read/Segment.php
  src/Read/ToggleStrategy.php
Labels: enhancement, dependencies

#43 [#18] Add StrategyWasRemoved event
  src/Write/Event/StrategyWasRemoved.php
  src/Write/Feature.php
  test/Write/FeatureTest.php
Labels: enhancement

#44 [#17] Add StrategyWasAdded event
  src/Write/Event/StrategyWasAdded.php
  src/Write/Feature.php
  src/Write/Payload.php
  src/Write/Segment.php
  src/Write/Strategy.php
  test/Write/FeatureTest.php
Labels: enhancement

#42 [#41] Run CI both PHP 7.4 and 8.0
  .github/workflows/coding-standards.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
Labels: dependencies

#46 [#45] define psalm types for arrays
  src/Read/ChainSegmentFactory.php
  src/Read/ChainToggleStrategyFactory.php
  src/Read/Feature.php
  src/Read/Segment.php
  src/Read/SegmentFactory.php
  src/Read/ToggleStrategies.php
  src/Read/ToggleStrategy.php
  src/Write/Feature.php
  src/Write/Payload.php
  src/Write/Strategy.php
Labels: enhancement

#47 [#45] fix feature psalm types
  src/Read/Feature.php
Labels: bug, enhancement

#48 [#35] Add PHP 8.1 support
  .github/workflows/coding-standards.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  composer.json
  phpcs.xml.dist
Labels: enhancement, good first issue, dependencies, Hacktoberfest
